<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>com.github.drakescraft_labs</groupId>
    <artifactId>SlimeTinker-drake</artifactId>
    <version>1.2.1-Drake</version>

    <name>SlimeTinker</name>
    <description>Slimefun4 Addon SlimeTinker</description>
    <url>https://github.com/SlimefunNewHorizons/SlimeTinker-drake</url>

    <licenses>
        <license>
            <name>GPL-3.0 license</name>
            <url>https://github.com/SlimefunNewHorizons/SlimeTinker-drake/blob/1.21-latin/LICENSE</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <developers>
        <developer>
            <name>Sefiraat</name>
            <organization>Autor original</organization>
        </developer>
        <developer>
            <name>DrakesCraft Labs</name>
            <organization>DrakesCraft Labs</organization>
            <organizationUrl>https://github.com/DrakesCraft-Labs</organizationUrl>
        </developer>
    </developers>

    <scm>
        <connection>scm:git:git://github.com/SlimefunNewHorizons/SlimeTinker-drake.git</connection>
        <developerConnection>scm:git:ssh://github.com:SlimefunNewHorizons/SlimeTinker-drake.git</developerConnection>
        <url>https://github.com/SlimefunNewHorizons/SlimeTinker-drake/tree/1.21-latin</url>
    </scm>

    <properties>
        <maven.deploy.skip>false</maven.deploy.skip>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.build.number>MODIFIED</project.build.number>
        <paper.version>1.21.1-R0.1-SNAPSHOT</paper.version>
        <slimefun.version>RC-37</slimefun.version>
        <infinitylib.version>7e03c79</infinitylib.version>
        <acf.version>0.5.1-SNAPSHOT</acf.version>
        <dough.version>1.2.0</dough.version>
    </properties>

    <repositories>
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
        <repository>
            <id>papermc-repo</id>
            <url>https://repo.papermc.io/repository/maven-public/</url>
        </repository>
        <repository>
            <id>aikar</id>
            <url>https://repo.aikar.co/content/groups/aikar/</url>
        </repository>
    </repositories>

    <build>
        <finalName>${project.name} v${project.version}</finalName>
        <defaultGoal>clean package</defaultGoal>
        <sourceDirectory>${basedir}/src/main/java</sourceDirectory>
        <resources>
            <resource>
                <directory>${basedir}/src/main/resources</directory>
                <filtering>true</filtering>
                <includes>
                    <include>*</include>
                </includes>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.6.2</version>
                <configuration>
                    <minimizeJar>true</minimizeJar>
                    <relocations>
                        <relocation>
                            <pattern>io.github.mooy1.infinitylib</pattern>
                            <shadedPattern>io.github.sefiraat.slimetinker.infinitylib</shadedPattern>
                        </relocation>
                        <relocation>
                            <pattern>co.aikar.commands</pattern>
                            <shadedPattern>io.github.sefiraat.slimetinker.acf</shadedPattern>
                        </relocation>
                    </relocations>
                    <filters>
                        <filter>
                            <artifact>*:*</artifact>
                            <excludes>
                                <exclude>META-INF/*</exclude>
                            </excludes>
                        </filter>
                    </filters>
                </configuration>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.16.0</version>
                <configuration>
                    <source>21</source>
                    <target>21</target>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>io.papermc.paper</groupId>
            <artifactId>paper-api</artifactId>
            <version>${paper.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.github.Slimefun</groupId>
            <artifactId>Slimefun4</artifactId>
            <version>${slimefun.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>io.github.baked-libs</groupId>
            <artifactId>dough-api</artifactId>
            <version>${dough.version}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>io.github.mooy1</groupId>
            <artifactId>InfinityLib</artifactId>
            <version>${infinitylib.version}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>com.google.code.findbugs</groupId>
            <artifactId>annotations</artifactId>
            <version>3.0.1u2</version>
            <scope>provided</scope>
            <exclusions>
                <exclusion>
                    <groupId>net.jcip</groupId>
                    <artifactId>jcip-annotations</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.google.code.findbugs</groupId>
                    <artifactId>jsr305</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>co.aikar</groupId>
            <artifactId>acf-paper</artifactId>
            <version>${acf.version}</version>
            <scope>compile</scope>
        </dependency>
    
    </dependencies>
</project>
